apiVersion: v1
kind: Service
metadata:
  name: {{ include "testnet-chaindata.fullname" . }}
  labels:
    {{- include "testnet-chaindata.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
  {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol | default "TCP" }}
  {{- end }}
  selector:
    {{- include "testnet-chaindata.selectorLabels" . | nindent 4 }}
