apiVersion: v1
kind: PersistentVolume
metadata:
  name: wemix-node1-nfs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.10.1.15
    path: "/data/wemix-test"
