apiVersion: v1
kind: Service
metadata:
  name: {{ include "en-chart.fullname" . }}
  labels:
    {{- include "en-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: {{ (index .Values.service.ports 0).protocol }}
      port: {{ (index .Values.service.ports 0).port }}
      targetPort: {{ (index .Values.service.ports 0).targetPort }}
      #    - port: {{ .Values.service.ports.port }}
      #      targetPort: http
      #      protocol: TCP
      #      name: http
  selector:
    {{- include "en-chart.selectorLabels" . | nindent 4 }}
