apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": "pre-install" # Hook 설정
    "helm.sh/hook-weight": "1" # 실행 순서를 제어 (작은 숫자가 먼저 실행)